[package]
name = "mongodb-test"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.6.0"
# tokio = {"version"= "1.29.1", features=["rt-threaded", "macros"]}
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
tokio = "1.29.1"